version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://app:app@postgres:5432/app?sslmode=disable
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=8080
      - LOG_LEVEL=info
      - MATCHMAKING_BOT_TIMEOUT_SEC=30
      - TURN_TIMEOUT_SEC=45
    volumes:
      - ./.env.dev:/root/.env.dev

volumes:
  postgres_data:
